#!/bin/zsh

DOTFILES_DIR="$HOME/dotfiles"

dotfiles() {

  if [ $# -eq 0 ]; then
    cd "$DOTFILES_DIR" && nvim
    exit 0
  fi

  local command=$1
  case "$command" in
    init)
      bash "$DOTFILES_DIR/init.sh"
      ;;
    update)
      bash "$DOTFILES_DIR/update.sh"
      ;;
    git)
      bash "$DOTFILES_DIR/bash/_setup_git.sh"
      ;;
    ahk)
      bash "$DOTFILES_DIR/bash/_setup_ahk.sh"
      ;;
    *)
      echo "Unknown command: $command"
      exit 1
      ;;
  esac
}

dotfiles $@
