default_flags = "-ih --sort-by-type-dirs-first"

[[verbs]]
key = "enter"
execution = "~/.config/broot/open_file.sh {file}"
apply_to = "file"
leave_broot = false

[[verbs]]
invocation = "preview"
key = "ctrl-p"
internal = "toggle_preview"
apply_to = "file"

[[verbs]]
key = "c"
execution = "bash -c 'touch {file}'"
apply_to = "directory"

[[verbs]]
invocation = "z"
execution = ":toggle_tree"
apply_to = "directory"
