gui:
  theme:
    selectedLineBgColor:
      - "#30363f"
  expandFocusedSidePanel: true
customCommands:
  - key: "<C-p>"
    description: "Pull (force)"
    context: "localBranches"
    command: 'git stash save "stashed by force pull" && git fetch && git reset --hard origin/$(git rev-parse --abbrev-ref @)'
    prompts:
      - type: "confirm"
        title: "Pull (force)"
        body: "Are you sure you want to force pull? (Your local changes will be stashed.)"
  - key: "<c-space>"
    description: "Checkout (with auto-stash and auto-pop)"
    context: "localBranches"
    command: 'git stash save "auto-stash" && git checkout {{ .SelectedLocalBranch.Name }} && git stash pop'
os:
  editPreset: "nvim-remote"
git:
  paging:
    colorArg: always
    pager: delta -n -s --dark --paging=never
