name: Execute init.sh on WSL

on: [push]

jobs:
  run-initializer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Grant execute permissions for init.sh
        run: chmod +x ./init.sh

      - name: Run init.sh
        shell: bash
        run: ./init.sh
