name: Execute init.sh on ubuntu-latest

on:
  push:
    paths:
      - init.sh
      - .github/workflows/run-initializer.yml

jobs:
  run-initializer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Grant execute permissions for init.sh
        run: chmod +x ./init.sh

      - name: Run init.sh
        shell: bash
        run: ./init.sh
